name: push docker image to ghcr CI pipelinw
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: action/checkout@v3
    - name: Push docker image to ghcr
      run : | 
        docker login -u Shravankamble -p {{ secrets.GT.ACTION }} ghcr.io
        docker build -t ghcr.io/Shravankamble/jwt-auth:v1 .
        docker push ghcr.io/Shravankamble/jwt-auth:v1