name: push docker image to ghcr CI pipeline
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Push docker image to ghcr
      run : | 
        docker login -u Shravankamble -p ${{ secrets.GT_TOKEN }} ghcr.io
        docker build -t ghcr.io/shravankamble/jwt-auth:v2 .
        docker push ghcr.io/shravankamble/jwt-auth:v2