name: push docker image to ghcr CI pipeline
on: 
  push:
    branches: ["main"]

jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: testing endpoints
      run: |
        pip install pytest
        make tests

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Push docker image to ghcr
      run : | 
        docker login -u Shravankamble -p ${{ secrets.GT_TOKEN }} ghcr.io
        docker build -t ghcr.io/shravankamble/jwt-auth:v1 .
        docker sbom --format spdx-json --output spdx.json ghcr.io/shravankamble/jwt-auth:v1
        docker push ghcr.io/shravankamble/jwt-auth:v1